### ISSUE TITLE
Article hikikomori/otaku

### ISSUE THREAD

**Issue by 0xadada** [visual-assault/visual-assault.github.io#13]
Want to publish article on hikikomori/otaku with a new PDF link, with redirects from the old original URLs.

## Todo
- [x] Find old URLs linking to article
- [ ] Rewrite article into markdown
- [ ] Convert to PDF
